### ISSUE TITLE
Import Error with Nuxt 3

### ISSUE THREAD

**Issue by talhabw** [antfu/drauu#24]
### Describe the bug

I am trying to use it in my Nuxt 3 project. I get this error:

```js
import { getStroke } from "perfect-freehand";
         ^^^^^^^^^
SyntaxError: Named export 'getStroke' not found. The requested module 'perfect-freehand' is a CommonJS module, which may not support all module.exports as named exports.       
CommonJS modules can always be imported via the default export, for example using:      

import pkg from 'perfect-freehand';
const { getStroke } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async __instantiateModule__ (file:///C:/Users/talha/code/kodesis-nuxt/.nuxt/dist/server/server.mjs:31957:3)
```

### Reproduction

[Codesandbox](https://codesandbox.io/s/interesting-agnesi-6wup42?file=/app.vue)

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 3.82 GB / 15.79 GB
  Binaries:
    Node: 16.16.0 - ~\.nvm\versions\node\v16.16.0\bin\node.EXE
    Yarn: 1.22.19 - ~\.yarn\bin\yarn.CMD
    npm: 8.11.0 - ~\.nvm\versions\node\v16.16.0\bin\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mahapo** [comment]
@antfu @talhabw +1 This Error iss still present in Nuxt

![image](https://github.com/antfu/drauu/assets/28730855/2ca1226a-13fe-4f04-8b68-a39707040f6e)


```
build: {
   transpile: ["perfect-freehand"],
}
```
 and
```
 optimizeDeps: {
     include: ["perfect-freehand"],
 },
```

didn't helped
