### ISSUE TITLE
I want to know how to use this

### ISSUE THREAD

**Issue by rational-stars** [antfu/drauu#35]
<img width="959" alt="image" src="https://github.com/antfu/drauu/assets/65513250/4ebb9475-5d29-40a8-bd98-1e19cfed6373">
<img width="696" alt="image" src="https://github.com/antfu/drauu/assets/65513250/e116e7a7-f8ba-4a36-a65e-7e0cd426bc5b">
Why can't I load these two methods?

**Comment by antfu** [comment]
It seems like this issue is not following the issue template. Closing.

Please **follow the issue template** with all the required information and create a new one.
